services:
  web:
    build: .
    container_name: data-to-db
    ports:
      - "6969:6969" # Data upload server
    volumes:
      - ./app/data:/app/data
      - ./app/templates:/app/templates
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
